name: synth #Mac for evaluation (note ##)
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h6c40b1e_6
  - ca-certificates=2025.7.15=hecd8cb5_0
  - expat=2.7.1=h6d0c2b6_0
  - libcxx=19.1.7=haebbb44_3 ##
  - libffi=3.4.4=hecd8cb5_1
  - ncurses=6.5=h923df54_0 ##
  - openssl=3.0.17=hee2dfae_0
  - pip=25.1=pyhc872135_2
  - python=3.12.11=he8d2d4c_0
  - readline=8.3=h49f2429_0 ##
  - setuptools=78.1.1=py312hecd8cb5_0
  - sqlite=3.50.2=hc8b0dd6_1
  - tk=8.6.15=h3a5a201_0
  - wheel=0.45.1=py312hecd8cb5_0
  - xz=5.6.4=h46256e1_1
  - zlib=1.2.13=h4b97444_1
  - pip:
      - absl-py==2.3.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - attrs==25.3.0
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - click==8.3.0
      - colorama==0.4.6
      - contourpy==1.3.3
      - cycler==0.12.1
      - datasets==4.0.0
      - dill==0.3.8
      - evaluate==0.4.6
      - filelock==3.19.1
      - fonttools==4.60.1
      - frozenlist==1.7.0
      - fsspec==2025.3.0
      - hf-xet==1.1.8
      - huggingface-hub==0.34.4
      - idna==3.10
      - jinja2==3.1.6
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - lxml==6.0.2
      - markupsafe==3.0.2
      - matplotlib==3.10.7
      - mpmath==1.3.0
      - multidict==6.6.4
      - multiprocess==0.70.16
      - networkx==3.5
      - nltk==3.9.2
      - numpy==1.26.4
      - packaging==25.0
      - pandas==2.3.2
      - pillow==11.3.0
      - portalocker==3.2.0
      - propcache==0.3.2
      - protobuf==6.33.0
      - pyarrow==21.0.0
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2025.7.34
      - requests==2.32.5
      - rouge-score==0.1.2
      - sacrebleu==2.5.1
      - sacremoses==0.1.1
      - safetensors==0.6.2
      - seaborn==0.13.2
      - sentencepiece==0.2.1
      - six==1.17.0
      - sympy==1.14.0
      - tabulate==0.9.0
      - tokenizers==0.21.4
      - torch==2.2.2 ##
      - torchaudio==2.2.2 ##
      - torchvision==0.17.2 ##
      - tqdm==4.67.1
      - transformers==4.55.3
      - typing-extensions==4.14.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - xxhash==3.5.0
      - yarl==1.20.1
prefix: /opt/anaconda3/envs/synth
